Link fuse-client with libmarfs, instead of object-files
This allows distinct calls to make to do build and mount, in the case where
e.g. some special ojbect-files are needed.  The problem was something like
this:

    $ make clean && make lean SPINLOCKS=1
    $ make mnt
    object_stream.o: In function `stream_get':
    object_stream.c:(.text+0x21e): undefined reference to `PSL_post'
    object_stream.c:(.text+0x22f): undefined reference to `PSL_wait_with_timeout'
    [...]

Fixed by just linking with the library.